<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOU3AxEZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOU3AxEZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOU3AxEZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOU3AxEZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOU3AxEZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OU3AxEZ',
    'container.build_id' => '0f9f1a6d',
    'container.build_time' => 1585215228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOU3AxEZ');
