<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHXAzdms\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHXAzdms/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHXAzdms.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHXAzdms\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHXAzdms\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HXAzdms',
    'container.build_id' => 'fb4846ed',
    'container.build_time' => 1585221385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHXAzdms');
