<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'admin_aliment' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminAlimentController::index'], [], [['text', '/admin/aliment']], [], []],
    'admin_aliment_creation' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminAlimentController::ajoutEtModif'], [], [['text', '/admin/aliment/creation']], [], []],
    'admin_aliment_modification' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminAlimentController::ajoutEtModif'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/aliment']], [], []],
    'admin_aliment_suppression' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminAlimentController::suppression'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/aliment']], [], []],
    'admin_types' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTypeController::index'], [], [['text', '/admin/type']], [], []],
    'ajoutType' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTypeController::ajoutEtModif'], [], [['text', '/admin/type/create']], [], []],
    'modifType' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminTypeController::ajoutEtModif'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/type']], [], []],
    'deleteType' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminTypeController::deleteType'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/type']], [], []],
    'aliments' => [[], ['_controller' => 'App\\Controller\\AlimentController::index'], [], [['text', '/']], [], []],
    'alimentsParCalorie' => [['calorie'], ['_controller' => 'App\\Controller\\AlimentController::alimentsMoinsCaloriques'], [], [['variable', '/', '[^/]++', 'calorie'], ['text', '/aliments/calorie']], [], []],
    'alimentsParGlucide' => [['glucide'], ['_controller' => 'App\\Controller\\AlimentController::alimentsAvecMoinsGlucides'], [], [['variable', '/', '[^/]++', 'glucide'], ['text', '/aliments/glucide']], [], []],
    'types' => [[], ['_controller' => 'App\\Controller\\TypeController::index'], [], [['text', '/types']], [], []],
];
